#configs

# Configure environment
###############################################################################
threads: 8

SAMPLE_DIR: /home/data/ssmstest/reads/

OUTPUT_DIR: /home/david/MEIJI/

INDEX_DIR: /home/data/db/gtdb/bbmap/
